# encoding: utf-8

Country.create([
                      
                            {name: "Adana"},
							{name: "Adıyaman"},
							{name:"Afyon "},
							{name:"Ağrı  "},
							{name:"Amasya "},
							{name:"Antalya "},
							{name:"Artvin  "},
							{name:"Aydın   "},
							{name:"Balıkesir"},
							{name:"Bilecik "},
							{name:"Bitlis"},
							{name:"Bolu "},
							{name:"Burdur "},
							{name:"Bursa "},
							{name:"Çanakkale  "},
							{name:"Çankırı"},
							{name:"Çorum"},
							{name:"Denizli"},
							{name:"Diyarbakır "},
							{name:"Edirne "},
							{name:"Elazığ "},
							{name:"Erzurum "},
							{name:"Eskişehir  "},
							{name:"Giresun  "},
							{name:"Gümüşhane "},
							{name:"Hakkari  "},
							{name:"Hatay   "},
							{name:"Isparta"},
							{name:"İçel    "},
							{name:"İstanbul "},
							{name:"İzmir  "},
							{name:"Kars    "},
							{name:"Kastamonu  "},
							{name:"Kayseri  "},
							{name:"Kırklareli  "},
							{name:"Kırşehir "},
							{name:"Kocaeli  "},
							{name:"Konya   "},
							{name:"Kütahya  "},
							{name:"Malatya  "},
							{name:"Manisa  "},
							{name:"Kahramanmaraş "},
							{name:"Mardin   "},
							{name:"Muğla     "},
							{name:"Muş      "},
							{name:"Nevşehir  "},
							{name:"Niğde     "},
							{name:"Rize      "},
							{name:"Sakarya   "},
							{name:"Samsun    "},
							{name:"Siirt     "},
							{name:"Sinop     "},
							{name:"Sivas     "},
							{name:"Tekirdağ  "},
							{name:"Tokat     "},
							{name:"Trabzon   "},
							{name:"Tunceli   "},
							{name:"Şanlıurfa "},
							{name:"Uşak	"},
							{name:"Van     "},
							{name:"Yozgat    "},
							{name:"Zonguldak "},
							{name:"Aksaray  "},
							{name:"Bayburt  "},
							{name:"Karaman  "},
							{name:"Kırıkkale "},
							{name:"Batman    "},
							{name:"Şırnak   "},
							{name:"Bartın   "},
							{name:"Ardahan  "},
							{name:"Iğdır   "},
							{name:"Yalova  "},
							{name:"Karabük  "},
							{name:"Osmaniye  "},
							{name:"Düzce     "}
                              
                              
])
